Remove replacement parameter from zon.as (#3208)
I also added some more error handling in some places where it was
missing and easy to add (this also uncovered a minor configuration
error: The lamps didn't specify a model)
first step towards #3202